vim.pack.add({
  { src = "https://github.com/catppuccin/nvim" },
  { src = "https://github.com/nvim-mini/mini.nvim" },
  { src = "https://github.com/lewis6991/gitsigns.nvim" },
  { src = "https://github.com/gcmt/wildfire.vim" },
  { src = "https://github.com/psliwka/vim-smoothie" },
  { src = "https://github.com/ibhagwan/fzf-lua" },
  { src = "https://github.com/nvim-lualine/lualine.nvim" },
  { src = "https://github.com/kyazdani42/nvim-web-devicons" },
  { src = "https://github.com/andymass/vim-matchup" },
  { src = "https://github.com/szw/vim-maximizer" },
  { src = "https://github.com/neovim/nvim-lspconfig" },
  { src = "https://github.com/folke/trouble.nvim" },
  { src = "https://github.com/MattesGroeger/vim-bookmarks" },
  { src = "https://github.com/dustier/cli-bridge.nvim" },
  { src = "https://github.com/hrsh7th/nvim-cmp" },
  { src = "https://github.com/hrsh7th/cmp-nvim-lsp" },
  { src = "https://github.com/hrsh7th/cmp-path" },
  { src = "https://github.com/hrsh7th/cmp-buffer" },
  { src = "https://github.com/nvim-treesitter/nvim-treesitter", version = "master" },
  { src = "https://github.com/nvim-treesitter/nvim-treesitter-context" },
})
